const players = [
  {
    id: 1,
    name: "Rohit Sharma",
    role: "Batsman",
    runs: 8500,
    emoji: "🏏",
  },
  {
    id: 2,
    name: "Virat Kohli",
    role: "Batsman",
    runs: 12000,
    emoji: "🏏",
  },
  {
    id: 3,
    name: "Shubman Gill",
    role: "Batsman",
    runs: 4500,
    emoji: "🏏",
  },
  {
    id: 4,
    name: "KL Rahul",
    role: "Wicket Keeper",
    runs: 5200,
    emoji: "🧤",
  },
  {
    id: 5,
    name: "Hardik Pandya",
    role: "All Rounder",
    runs: 2200,
    emoji: "⭐",
  },
  {
    id: 6,
    name: "Ravindra Jadeja",
    role: "All Rounder",
    runs: 2800,
    emoji: "⭐",
  },
  {
    id: 7,
    name: "Jasprit Bumrah",
    role: "Bowler",
    runs: 400,
    emoji: "🎯",
  },
  {
    id: 8,
    name: "Mohammed Shami",
    role: "Bowler",
    runs: 350,
    emoji: "🎯",
  },
  {
    id: 9,
    name: "Kuldeep Yadav",
    role: "Bowler",
    runs: 250,
    emoji: "🎯",
  },
  {
    id: 10,
    name: "Mohammed Siraj",
    role: "Bowler",
    runs: 180,
    emoji: "🎯",
  },
  {
    id: 11,
    name: "Rishabh Pant",
    role: "Wicket Keeper",
    runs: 3200,
    emoji: "🧤",
  },
  {
    id: 12,
    name: "Shreyas Iyer",
    role: "Batsman",
    runs: 3000,
    emoji: "🏏",
  },
  {
    id: 13,
    name: "Axar Patel",
    role: "All Rounder",
    runs: 900,
    emoji: "⭐",
  },
  {
    id: 14,
    name: "Vaibhav Suryavanshi",
    role: "Batsman",
    runs: 150,
    emoji: "🏏",
  },
  {
    id: 15,
    name: "Kunal Pandya",
    role: "All Rounder",
    runs: 1500,
    emoji: "⭐",
  },
];

export default players;